add_test( [==[B3.1 Tick spacing]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B3.1 Tick spacing]==]  )
set_tests_properties( [==[B3.1 Tick spacing]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B3.2 Row spacing]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B3.2 Row spacing]==]  )
set_tests_properties( [==[B3.2 Row spacing]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B3.3 Non-integer samplesPerTick]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B3.3 Non-integer samplesPerTick]==]  )
set_tests_properties( [==[B3.3 Non-integer samplesPerTick]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B3.4 Tempo change mid-playback]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B3.4 Tempo change mid-playback]==]  )
set_tests_properties( [==[B3.4 Tempo change mid-playback]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B3.5 Chunk-size invariance]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B3.5 Chunk-size invariance]==]  )
set_tests_properties( [==[B3.5 Chunk-size invariance]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B3.6 BPM clamping]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B3.6 BPM clamping]==]  )
set_tests_properties( [==[B3.6 BPM clamping]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B4.1 Phrase loops]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B4.1 Phrase loops]==]  )
set_tests_properties( [==[B4.1 Phrase loops]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B4.2 Chain walks phrases]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B4.2 Chain walks phrases]==]  )
set_tests_properties( [==[B4.2 Chain walks phrases]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B4.3 Song walks chains]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B4.3 Song walks chains]==]  )
set_tests_properties( [==[B4.3 Song walks chains]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B4.4 Full 16-row chain]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B4.4 Full 16-row chain]==]  )
set_tests_properties( [==[B4.4 Full 16-row chain]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B4.5 Empty song does not hang]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B4.5 Empty song does not hang]==]  )
set_tests_properties( [==[B4.5 Empty song does not hang]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B4.7 Transpose]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B4.7 Transpose]==]  )
set_tests_properties( [==[B4.7 Transpose]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B4.6 Eight independent tracks]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B4.6 Eight independent tracks]==]  )
set_tests_properties( [==[B4.6 Eight independent tracks]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B4.8 Transpose clamping]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B4.8 Transpose clamping]==]  )
set_tests_properties( [==[B4.8 Transpose clamping]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B4.10 Empty chain = rest, not skip]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B4.10 Empty chain = rest\, not skip]==]  )
set_tests_properties( [==[B4.10 Empty chain = rest, not skip]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B4.9 Fuzz the walker]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B4.9 Fuzz the walker]==]  )
set_tests_properties( [==[B4.9 Fuzz the walker]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B5.1 DEL]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B5.1 DEL]==]  )
set_tests_properties( [==[B5.1 DEL]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B5.2 DEL clamped]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B5.2 DEL clamped]==]  )
set_tests_properties( [==[B5.2 DEL clamped]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B5.3 KIL]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B5.3 KIL]==]  )
set_tests_properties( [==[B5.3 KIL]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B5.5 HOP]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B5.5 HOP]==]  )
set_tests_properties( [==[B5.5 HOP]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B5.4 KIL clamped]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B5.4 KIL clamped]==]  )
set_tests_properties( [==[B5.4 KIL clamped]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B5.6 HOP clamped]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B5.6 HOP clamped]==]  )
set_tests_properties( [==[B5.6 HOP clamped]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B5.7 HOP interaction with PLAY_CHAIN]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B5.7 HOP interaction with PLAY_CHAIN]==]  )
set_tests_properties( [==[B5.7 HOP interaction with PLAY_CHAIN]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B5.9 Swing groove]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B5.9 Swing groove]==]  )
set_tests_properties( [==[B5.9 Swing groove]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B5.8 Groove length limits]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B5.8 Groove length limits]==]  )
set_tests_properties( [==[B5.8 Groove length limits]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B5.10 Groove index advance]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B5.10 Groove index advance]==]  )
set_tests_properties( [==[B5.10 Groove index advance]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B5.11 Groove index bounds]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B5.11 Groove index bounds]==]  )
set_tests_properties( [==[B5.11 Groove index bounds]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B6.1 ParamID round trip]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B6.1 ParamID round trip]==]  )
set_tests_properties( [==[B6.1 ParamID round trip]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B6.5 PlayMode values pinned]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B6.5 PlayMode values pinned]==]  )
set_tests_properties( [==[B6.5 PlayMode values pinned]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B6.6 Playhead row identity]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B6.6 Playhead row identity]==]  )
set_tests_properties( [==[B6.6 Playhead row identity]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B6.7 Engine-initiated stop is visible]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B6.7 Engine-initiated stop is visible]==]  )
set_tests_properties( [==[B6.7 Engine-initiated stop is visible]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B6.8 PLAY_START latency]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B6.8 PLAY_START latency]==]  )
set_tests_properties( [==[B6.8 PLAY_START latency]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B6.2 Ring overflow resync]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B6.2 Ring overflow resync]==]  )
set_tests_properties( [==[B6.2 Ring overflow resync]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B6.3 Playhead after stop]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B6.3 Playhead after stop]==]  )
set_tests_properties( [==[B6.3 Playhead after stop]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B6.4 Playhead is never stale]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B6.4 Playhead is never stale]==]  )
set_tests_properties( [==[B6.4 Playhead is never stale]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B6.9 Playhead packing round-trip]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B6.9 Playhead packing round-trip]==]  )
set_tests_properties( [==[B6.9 Playhead packing round-trip]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B7.1 Load and play]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B7.1 Load and play]==]  )
set_tests_properties( [==[B7.1 Load and play]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B7.4 Handle bounds]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B7.4 Handle bounds]==]  )
set_tests_properties( [==[B7.4 Handle bounds]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B7.2 Reload sample while playing]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B7.2 Reload sample while playing]==]  )
set_tests_properties( [==[B7.2 Reload sample while playing]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B7.3 GC ring drained exactly once]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B7.3 GC ring drained exactly once]==]  )
set_tests_properties( [==[B7.3 GC ring drained exactly once]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B7.5 Null sample]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B7.5 Null sample]==]  )
set_tests_properties( [==[B7.5 Null sample]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B7.6 Sample-rate conversion]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B7.6 Sample-rate conversion]==]  )
set_tests_properties( [==[B7.6 Sample-rate conversion]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[S1 START=0x80 on ramp -> first output ~0.5]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[S1 START=0x80 on ramp -> first output ~0.5]==]  )
set_tests_properties( [==[S1 START=0x80 on ramp -> first output ~0.5]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[S2 FWD one-shot terminates]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[S2 FWD one-shot terminates]==]  )
set_tests_properties( [==[S2 FWD one-shot terminates]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[S3 LENGTH=0x00 plays >=1 frame, no hang]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[S3 LENGTH=0x00 plays >=1 frame\, no hang]==]  )
set_tests_properties( [==[S3 LENGTH=0x00 plays >=1 frame, no hang]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[S4 FWD one-shot finishes and stays silent]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[S4 FWD one-shot finishes and stays silent]==]  )
set_tests_properties( [==[S4 FWD one-shot finishes and stays silent]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[S5 REV plays descending ramp]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[S5 REV plays descending ramp]==]  )
set_tests_properties( [==[S5 REV plays descending ramp]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[S6 FWDLOOP region model - loop within sample]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[S6 FWDLOOP region model - loop within sample]==]  )
set_tests_properties( [==[S6 FWDLOOP region model - loop within sample]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[S7 FWD_PP produces triangle-like shape]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[S7 FWD_PP produces triangle-like shape]==]  )
set_tests_properties( [==[S7 FWD_PP produces triangle-like shape]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[S9 Stereo sample L=+1 R=-1]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[S9 Stereo sample L=+1 R=-1]==]  )
set_tests_properties( [==[S9 Stereo sample L=+1 R=-1]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[S10 C-4 on 48kHz -> ratio exactly 1.0]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[S10 C-4 on 48kHz -> ratio exactly 1.0]==]  )
set_tests_properties( [==[S10 C-4 on 48kHz -> ratio exactly 1.0]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[S14 OSC mode ignores START]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[S14 OSC mode ignores START]==]  )
set_tests_properties( [==[S14 OSC mode ignores START]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[S15 One-shot reads final frame (ASan clean)]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[S15 One-shot reads final frame (ASan clean)]==]  )
set_tests_properties( [==[S15 One-shot reads final frame (ASan clean)]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[S16 Gate has no click]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[S16 Gate has no click]==]  )
set_tests_properties( [==[S16 Gate has no click]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[S17 One-shot has no midway dip]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[S17 One-shot has no midway dip]==]  )
set_tests_properties( [==[S17 One-shot has no midway dip]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[S18 Two instruments same path share one pool entry]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[S18 Two instruments same path share one pool entry]==]  )
set_tests_properties( [==[S18 Two instruments same path share one pool entry]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[S19 Both instruments re-pointed, buffer freed once]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[S19 Both instruments re-pointed\, buffer freed once]==]  )
set_tests_properties( [==[S19 Both instruments re-pointed, buffer freed once]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[S20 Fuzz - random SamplerState x random samples]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[S20 Fuzz - random SamplerState x random samples]==]  )
set_tests_properties( [==[S20 Fuzz - random SamplerState x random samples]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[S21 Pool full - incoming freed via GC]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[S21 Pool full - incoming freed via GC]==]  )
set_tests_properties( [==[S21 Pool full - incoming freed via GC]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[M1 AHD at 120 BPM, hold=6 holds full for 6000 samples]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[M1 AHD at 120 BPM\, hold=6 holds full for 6000 samples]==]  )
set_tests_properties( [==[M1 AHD at 120 BPM, hold=6 holds full for 6000 samples]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[M2 Same AHD at 60 BPM - stages 2x longer]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[M2 Same AHD at 60 BPM - stages 2x longer]==]  )
set_tests_properties( [==[M2 Same AHD at 60 BPM - stages 2x longer]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[M3 ATK=0 is instantaneous, no NaN]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[M3 ATK=0 is instantaneous\, no NaN]==]  )
set_tests_properties( [==[M3 ATK=0 is instantaneous, no NaN]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[M4 AHD -> VOLUME, AMT=0xFF gain follows envelope]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[M4 AHD -> VOLUME\, AMT=0xFF gain follows envelope]==]  )
set_tests_properties( [==[M4 AHD -> VOLUME, AMT=0xFF gain follows envelope]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[M5 ADSR gate on/off - sustain holds, release runs]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[M5 ADSR gate on/off - sustain holds\, release runs]==]  )
set_tests_properties( [==[M5 ADSR gate on/off - sustain holds, release runs]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[M7 LFO RETRIG resets phase at note-on]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[M7 LFO RETRIG resets phase at note-on]==]  )
set_tests_properties( [==[M7 LFO RETRIG resets phase at note-on]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[M9 LFO FREQ=0x10 at 120 BPM period = 1 bar]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[M9 LFO FREQ=0x10 at 120 BPM period = 1 bar]==]  )
set_tests_properties( [==[M9 LFO FREQ=0x10 at 120 BPM period = 1 bar]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[M10 DEST=CUTOFF (0x06) affects filter]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[M10 DEST=CUTOFF (0x06) affects filter]==]  )
set_tests_properties( [==[M10 DEST=CUTOFF (0x06) affects filter]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[M13 Mod-to-mod: mod1 -> MOD AMT of mod2]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[M13 Mod-to-mod: mod1 -> MOD AMT of mod2]==]  )
set_tests_properties( [==[M13 Mod-to-mod: mod1 -> MOD AMT of mod2]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[M14 AMT polarity - 0x80 neutral, 0x00 inverted, 0xFF full]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[M14 AMT polarity - 0x80 neutral\, 0x00 inverted\, 0xFF full]==]  )
set_tests_properties( [==[M14 AMT polarity - 0x80 neutral, 0x00 inverted, 0xFF full]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[M18 Fuzz - random mod bytes x render: no crash, no NaN]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[M18 Fuzz - random mod bytes x render: no crash\, no NaN]==]  )
set_tests_properties( [==[M18 Fuzz - random mod bytes x render: no crash, no NaN]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[B8.5 TSan smoke test]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[B8.5 TSan smoke test]==]  )
set_tests_properties( [==[B8.5 TSan smoke test]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
add_test( [==[Demo song offline verification]==] C:/dev/m8-sdl3/build_render/Release/m8_tests.exe [==[Demo song offline verification]==]  )
set_tests_properties( [==[Demo song offline verification]==] PROPERTIES WORKING_DIRECTORY C:/dev/m8-sdl3/build_render)
set( m8_tests_TESTS [==[B3.1 Tick spacing]==] [==[B3.2 Row spacing]==] [==[B3.3 Non-integer samplesPerTick]==] [==[B3.4 Tempo change mid-playback]==] [==[B3.5 Chunk-size invariance]==] [==[B3.6 BPM clamping]==] [==[B4.1 Phrase loops]==] [==[B4.2 Chain walks phrases]==] [==[B4.3 Song walks chains]==] [==[B4.4 Full 16-row chain]==] [==[B4.5 Empty song does not hang]==] [==[B4.7 Transpose]==] [==[B4.6 Eight independent tracks]==] [==[B4.8 Transpose clamping]==] [==[B4.10 Empty chain = rest, not skip]==] [==[B4.9 Fuzz the walker]==] [==[B5.1 DEL]==] [==[B5.2 DEL clamped]==] [==[B5.3 KIL]==] [==[B5.5 HOP]==] [==[B5.4 KIL clamped]==] [==[B5.6 HOP clamped]==] [==[B5.7 HOP interaction with PLAY_CHAIN]==] [==[B5.9 Swing groove]==] [==[B5.8 Groove length limits]==] [==[B5.10 Groove index advance]==] [==[B5.11 Groove index bounds]==] [==[B6.1 ParamID round trip]==] [==[B6.5 PlayMode values pinned]==] [==[B6.6 Playhead row identity]==] [==[B6.7 Engine-initiated stop is visible]==] [==[B6.8 PLAY_START latency]==] [==[B6.2 Ring overflow resync]==] [==[B6.3 Playhead after stop]==] [==[B6.4 Playhead is never stale]==] [==[B6.9 Playhead packing round-trip]==] [==[B7.1 Load and play]==] [==[B7.4 Handle bounds]==] [==[B7.2 Reload sample while playing]==] [==[B7.3 GC ring drained exactly once]==] [==[B7.5 Null sample]==] [==[B7.6 Sample-rate conversion]==] [==[S1 START=0x80 on ramp -> first output ~0.5]==] [==[S2 FWD one-shot terminates]==] [==[S3 LENGTH=0x00 plays >=1 frame, no hang]==] [==[S4 FWD one-shot finishes and stays silent]==] [==[S5 REV plays descending ramp]==] [==[S6 FWDLOOP region model - loop within sample]==] [==[S7 FWD_PP produces triangle-like shape]==] [==[S9 Stereo sample L=+1 R=-1]==] [==[S10 C-4 on 48kHz -> ratio exactly 1.0]==] [==[S14 OSC mode ignores START]==] [==[S15 One-shot reads final frame (ASan clean)]==] [==[S16 Gate has no click]==] [==[S17 One-shot has no midway dip]==] [==[S18 Two instruments same path share one pool entry]==] [==[S19 Both instruments re-pointed, buffer freed once]==] [==[S20 Fuzz - random SamplerState x random samples]==] [==[S21 Pool full - incoming freed via GC]==] [==[M1 AHD at 120 BPM, hold=6 holds full for 6000 samples]==] [==[M2 Same AHD at 60 BPM - stages 2x longer]==] [==[M3 ATK=0 is instantaneous, no NaN]==] [==[M4 AHD -> VOLUME, AMT=0xFF gain follows envelope]==] [==[M5 ADSR gate on/off - sustain holds, release runs]==] [==[M7 LFO RETRIG resets phase at note-on]==] [==[M9 LFO FREQ=0x10 at 120 BPM period = 1 bar]==] [==[M10 DEST=CUTOFF (0x06) affects filter]==] [==[M13 Mod-to-mod: mod1 -> MOD AMT of mod2]==] [==[M14 AMT polarity - 0x80 neutral, 0x00 inverted, 0xFF full]==] [==[M18 Fuzz - random mod bytes x render: no crash, no NaN]==] [==[B8.5 TSan smoke test]==] [==[Demo song offline verification]==])
